<?php
defined( 'ABSPATH' ) || exit;
get_header();
?>
<main class="arden-page arden-projects-page">
	<?php arden_page_banner( 'HƠN 500.000+ SẢN PHẨM ĐÃ XUẤT XƯỞNG', 'DỰ ÁN & BỘ SƯU TẬP ĐÃ GIA CÔNG', 'Tham khảo các dòng sản phẩm thời trang thực tế đã sản xuất tại xưởng may Arden cho các đối tác thương hiệu Local Brand và doanh nghiệp.' ); ?>
	<section class="arden-project-archive"><div class="arden-container"><header class="arden-section-title"><p class="arden-eyebrow">DANH MỤC THỰC TẾ</p><h2>BỘ SƯU TẬP MẪU THEO TỪNG CHỦNG LOẠI</h2><p>Chọn từng danh mục sản phẩm bên dưới để xem hình ảnh thực tế, thông số vải và quy mô đặt may từng đơn hàng.</p></header>
	<div class="arden-project-tabs" role="tablist" aria-label="Lọc dự án"><button class="is-active" role="tab" aria-selected="true" data-project-filter="all">TẤT CẢ</button><button role="tab" aria-selected="false" data-project-filter="ao-thun">ÁO THUN</button><button role="tab" aria-selected="false" data-project-filter="ao-so-mi">ÁO SƠ MI</button><button role="tab" aria-selected="false" data-project-filter="quan">QUẦN</button><button role="tab" aria-selected="false" data-project-filter="ao-khoac">ÁO KHOÁC</button></div>
	<div class="arden-project-grid"><?php if ( have_posts() ) : while ( have_posts() ) : the_post(); $material = (string) get_post_meta( get_the_ID(), '_arden_material', true ); $minimum = (string) get_post_meta( get_the_ID(), '_arden_min_order', true ); $terms = wp_get_post_terms( get_the_ID(), 'project_category', array( 'fields' => 'slugs' ) ); ?><article <?php post_class( 'arden-project-card' ); ?> data-project-category="<?php echo esc_attr( implode( ' ', is_wp_error( $terms ) ? array() : $terms ) ); ?>"><a class="arden-project-card__media" href="<?php the_permalink(); ?>"><?php if ( has_post_thumbnail() ) { the_post_thumbnail( 'arden-card' ); } else { echo '<span class="arden-card__placeholder"></span>'; } ?></a><div class="arden-project-card__body"><p class="arden-project-card__badge">DỰ ÁN THỰC TẾ</p><h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3><p><?php echo do_shortcode( '[arden_icon name="scissors"]' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?> Vải: <?php echo esc_html( $material ? $material : 'Theo mẫu duyệt' ); ?></p><p><?php echo do_shortcode( '[arden_icon name="package"]' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?> MOQ: <?php echo esc_html( $minimum ? $minimum : 'Theo yêu cầu' ); ?></p><a class="arden-project-card__link" href="<?php the_permalink(); ?>">XEM THÔNG SỐ & MẪU <?php echo do_shortcode( '[arden_icon name="arrow-right"]' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></a></div></article><?php endwhile; endif; ?></div>
	</div></section>
	<?php echo do_shortcode( '[block id="arden-process"]' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
	<?php echo do_shortcode( '[block id="arden-cta"]' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
</main>
<?php get_footer(); ?>
