<?php
/** Template Name: Arden News Archive */
defined( 'ABSPATH' ) || exit;
$news = new WP_Query( array( 'post_type' => 'post', 'post_status' => 'publish', 'posts_per_page' => 5, 'ignore_sticky_posts' => true ) );
get_header();
?>
<main class="arden-page arden-news-page">
	<?php arden_page_banner( 'GÓC CHIA SẺ KINH NGHIỆM LOCAL BRAND', 'TIN TỨC & KIẾN THỨC MAY MẶC', 'Cập nhật kiến thức chuyên sâu về chất liệu vải, kỹ thuật may mặc công nghiệp và kinh nghiệm tối ưu chi phí cho các nhà sáng lập thương hiệu thời trang.' ); ?>
	<section class="arden-news-archive"><div class="arden-container">
		<div class="arden-news-controls"><div class="arden-news-tabs" role="tablist" aria-label="Danh mục bài viết"><button class="is-active" role="tab" aria-selected="true" data-news-filter="all">TẤT CẢ BÀI VIẾT</button><button role="tab" aria-selected="false" data-news-filter="kinh-nghiem">KINH NGHIỆM ĐẶT MAY</button><button role="tab" aria-selected="false" data-news-filter="vai">KIẾN THỨC CHẤT LIỆU VẢI</button><button role="tab" aria-selected="false" data-news-filter="quy-trinh">QUY TRÌNH SẢN XUẤT XƯỞNG</button></div><label class="arden-news-search"><?php echo do_shortcode( '[arden_icon name="search"]' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?><span class="screen-reader-text">Tìm kiếm bài viết</span><input type="search" placeholder="Tìm kiếm bài viết..."></label></div>
		<div class="arden-news-layout"><div class="arden-news-primary">
		<?php if ( $news->have_posts() ) : $news->the_post(); ?><article <?php post_class( 'arden-news-featured' ); ?> data-news-card><a class="arden-news-card__media" href="<?php the_permalink(); ?>"><?php the_post_thumbnail( 'large' ); ?></a><div class="arden-news-featured__body"><p class="arden-news-meta"><?php echo do_shortcode( '[arden_icon name="calendar"]' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?><?php echo esc_html( get_the_date() ); ?> · <?php echo do_shortcode( '[arden_icon name="clock"]' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?> 6 phút đọc</p><h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2><p><?php echo esc_html( wp_trim_words( get_the_excerpt(), 28 ) ); ?></p><a class="arden-button" href="<?php the_permalink(); ?>">ĐỌC BÀI VIẾT CHI TIẾT <?php echo do_shortcode( '[arden_icon name="arrow-right"]' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></a></div></article>
		<h3 class="arden-news-more-title">CÁC BÀI VIẾT KHÁC</h3><div class="arden-news-grid"><?php while ( $news->have_posts() ) : $news->the_post(); ?><article <?php post_class( 'arden-news-card' ); ?> data-news-card><a class="arden-news-card__media" href="<?php the_permalink(); ?>"><?php the_post_thumbnail( 'arden-card' ); ?></a><div class="arden-news-card__body"><p class="arden-news-meta"><?php echo esc_html( get_the_date() ); ?></p><h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3><p><?php echo esc_html( wp_trim_words( get_the_excerpt(), 18 ) ); ?></p><a href="<?php the_permalink(); ?>">ĐỌC BÀI VIẾT <?php echo do_shortcode( '[arden_icon name="arrow-right"]' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></a></div></article><?php endwhile; ?></div><?php endif; wp_reset_postdata(); ?>
		</div><aside class="arden-news-sidebar"><div class="arden-news-handbook"><?php echo do_shortcode( '[arden_icon name="book"]' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?><h3>CẨM NANG MAY GIA CÔNG LOCAL BRAND</h3><p>Tài liệu tổng hợp những lưu ý giúp thương hiệu tối ưu chi phí và chất lượng.</p><a class="arden-button" href="<?php echo esc_url( home_url( '/lien-he/' ) ); ?>">NHẬN TƯ VẤN KỸ THUẬT MIỄN PHÍ</a></div><div class="arden-news-contact"><p>CẦN TƯ VẤN TRỰC TIẾP?</p><strong>0901 234 567</strong></div></aside></div>
	</div></section>
	<?php echo do_shortcode( '[block id="arden-cta"]' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
</main>
<?php get_footer(); ?>
